PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?student ?professor
WHERE {
  ?student rdf:type :Student .
  ?student :hasLearnedFrom ?professor .
}