PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?light (COUNT(?spell) AS ?count)
WHERE {
  ?spell rdf:type :Spell .
  ?spell :hasLight ?light .
}
GROUP BY ?light
