PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


DELETE {{
  ?student :hasStarRating ?rating .
}}
INSERT {{
  ?student :hasStarRating 3 .
}}
WHERE {{
  {{
    SELECT ?house ((SUM(?points) / 25) AS ?baseValue)
    WHERE {{
      ?student rdf:type :Student .
      ?student :hasPoints ?points .
      ?student :hasAccount ?wizard .
      ?wizard :belongsToHouse ?house .
    }}
    GROUP BY ?house
  }}
  ?student rdf:type :Student .
  ?student :hasPoints ?points .
  ?student :hasAccount ?wizard .
  ?wizard :belongsToHouse ?house .
  FILTER (?points > (?baseValue * 2) && ?points <= (?baseValue * 3))
}}