PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {{

    GRAPH <http://hogwarts.edu/ontology.owl#> {{

        :Wizard_{max_wizard_id}
            :hasName "{name}" ;
            {gender}
            {species}
            {blood_type}
            {eye_color}
            {house}
            {wand}
            {patronus} .

        :Account_{max_account_id}
            :hasMechanographicalNumber {nmec};
            :hasPassword "{password}" ;
            :hasAccount :Wizard_{max_wizard_id} .

        :Student_{max_student_id}
            :belongsToSchool :School_1 ;
            :hasSchoolYear 1 ;
            :hasAccount :Wizard_{max_wizard_id} .

    }}
}}