PREFIX hogwarts: <http://hogwarts.edu/ontology#>

INSERT DATA {{

    GRAPH <http://hogwarts.edu/ontology#> {{

        :Wizard_{max_wizard_id}
            rdf:type :Wizard ;
            :hasName "{name}" .
            {gender}
            {species}
            {blood_type}
            {eye_color}
            {house}
            {wand}
            {patronus} .

        :Account_{max_account_id}
            rdf:type :Account ;
            :hasMechanographicalNumber {nmec}^^xsd:integer;
            :hasPassword "{password}" ;
            :hasAccount :Wizard_{max_wizard_id} .

        :Student_{max_student_id}
            rdf:type :Student ;
            :belongsToSchool :School_1 ;
            :hasSchoolYear 1 ;
            hogwarts:wizard :Wizard_{max_wizard_id} .

    }}
}}