PREFIX hogwarts: <http://hogwarts.edu/ontology#>

INSERT {{
  ?course hogwarts:teaches_spell ?spell
}}
WHERE {{
    ?spell hogwarts:_type "spell" .
    ?spell hogwarts:id "{spell_id}" .
    ?course hogwarts:_type "course" .
    ?course hogwarts:id "{course_id}"
}}