PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX hogwarts: <http://hogwarts.edu/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?type ?role
WHERE {{
    OPTIONAL {{
        ?role :hasAccount {wizard_id} .
        ?role rdf:type ?type .
        FILTER (?type IN (:Headmaster, :Professor, :Student))
    }}
}}