    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    PREFIX hogwarts: <http://hogwarts.edu/ontology#>
    SELECT
        ?name
    WHERE {{
        <http://hogwarts.edu/houses/{houseId}> hogwarts:name ?name .
    }}