PREFIX hogwarts: <http://hogwarts.edu/ontology#>

SELECT ?name ?wizardId
WHERE {{
    ?professor hogwarts:_type "professor" .
    ?professor hogwarts:wizard ?wizard .
    ?professor hogwarts:id ?wizardId .
    ?wizard hogwarts:name ?name

    FILTER(?wizardId != "{professor_id}")
}}