PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hogwarts: <http://hogwarts.edu/ontology#>
SELECT
    ?name
WHERE {{
    <{professor_uri}> hogwarts:wizard ?wizard .
    ?wizard hogwarts:name ?name
}}