PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX hogwarts: <http://hogwarts.edu/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?school_year (COUNT(?student) AS ?numberOfStudents)
WHERE {{
    ?student rdf:type :Student ;
             :hasSchoolYear ?school_year .
}}
GROUP BY ?school_year