PREFIX hogwarts: <http://hogwarts.edu/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT
?wizardId
WHERE
{{
    ?account rdfs:type "account" .
    ?account hogwarts:number {nmec_literal} .
    ?account hogwarts:password {password_literal} .
    ?account hogwarts:wizard ?wizard .
    ?wizard hogwarts:id ?wizardId
}}