PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://hogwarts.edu/ontology.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX hogwarts: <http://hogwarts.edu/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT 
 	(MAX(?wizardId) AS ?nextWizardId) 
    (MAX(?studentId) AS ?nextStudentId)
    (MAX(?accountId) AS ?nextAccountId)
WHERE {{
    ?wizard rdf:type :Wizard .
    BIND(xsd:integer(SUBSTR(STR(?wizard), STRLEN(STR(:Wizard_))+1)) AS ?wizardId) .
    
    ?student rdf:type :Student .
    BIND(xsd:integer(SUBSTR(STR(?student), STRLEN(STR(:Student_))+1)) AS ?studentId) .
                
    ?account rdf:type :Account .
    BIND(xsd:integer(SUBSTR(STR(?account), STRLEN(STR(:Account_))+1)) AS ?accountId) .
}}