PREFIX hogwarts: <http://hogwarts.edu/ontology#>

DELETE
{{
    {student_id} :learnsCourse {course_id}
}}
INSERT
{{
    {student_id} :hasLearnedCourse {course_id}
}}
WHERE {{
    {student_id} rdf:type :Student .
    {course_id} rdf:type :Course .
}}